data_source: 'microbiomeHD'
# it has to be 'microbiomeHD', 'CMD', or 'MIDASim'

src: './data'

dataset_name: 'autism_2_microbiomeHD'
# for MicrobiomeHD, the dataset_name is the name of the folder in the data folder where all the MicrobiomeHD datasets downloaded has to be saved

CMD_datasets: ["HMP_2019_ibdmdb", "LiJ_2014", "NielsenHB_2014"]
CMD_conditions: ['IBD', 'healthy']

RW_LIBSIZE_THRESHOLD: 0.05
RW_RELAB_THRESHOLD: 0.05

COVAR_L: []
# list of covariates to be used in the final stage of data cleaning/complete confounding calculations + data saving
# in our case, only ['disease', 'gender', 'age_category'] for CMD/IBD datasets are used, otherwise all empty

datatype: 'count'
# it has to be 'count' or 'relab'

rules_to_run: 'all' 
# one of the following: 'all', 'preprocess_or_simulate', 'data_integration', 'evaluation', 'visualization'