### GLOBAL VARS ###
rules_to_run: 'all_rw' 
# one of the following: 'all_rw', 'all_simulated', 'preprocess', 'simulate', 'data_integration', 'evaluation', 'visualization'

# data_source: 'microbiomeHD'
data_source: 'CMD'
# it has to be 'microbiomeHD', 'CMD', or 'MIDASim'

src: './data'

dataset_name: 'crc_3_CMD'
# for MicrobiomeHD, the dataset_name is the name of the folder in the data folder where all the MicrobiomeHD datasets downloaded has to be saved

datatype: 'relab'
# it has to be 'count' or 'relab'

### PREPROCESSING PHASE ###
CMD_datasets: ["FengQ_2015", "HanniganGD_2017", "ThomasAM_2018a", "YachidaS_2019", "ZellerG_2014"]
CMD_conditions: ["adenoma", "healthy"]

RW_LIBSIZE_THRESHOLD: 0.05
RW_RELAB_THRESHOLD: 0.05

COVAR_L: ["disease", "gender", "age"]
# list of covariates to be used in the final stage of data cleaning/complete confounding calculations + data saving
# in our case, only ['disease', 'gender', 'age_category'] for CMD/IBD datasets are used, otherwise all empty

### BENCHMARK PHASE ###
post_integration_outputs: './benchmark/benchmarked_results'
used_R_methods: ["combat", "limma", "MMUPHin", 'ConQuR_rel']
used_Python_methods: ['harmony', "percentile_norm"]
batch_ref: 'FengQ_2015'
covar: ["disease", "gender", "age"] # make sure that this column does not have NAs for every patient!
condition_value: 'CRC'

### EVALUATION PHASE ###
evaluation_outputs: './outputs'
binarizing_agent: 'adenoma' # for two microbiomeHD datasets or 'IBD' for ibd or 'adenoma' for the CRC dataset

