### GLOBAL VARS ###
rules_to_run: 'all_rw' 
# one of the following: 'all_rw', 'all_simulated', 'preprocess', 'simulate', 'data_integration', 'evaluation', 'visualization'

data_source: 'microbiomeHD'
# it has to be 'microbiomeHD', 'CMD', or 'MIDASim'

src: './data'

dataset_name: 'cdi_3_microbiomeHD'
# for MicrobiomeHD, the dataset_name is the name of the folder in the data folder where all the MicrobiomeHD datasets downloaded has to be saved

datatype: 'count'
# it has to be 'count' or 'relab'

### PREPROCESSING PHASE ###
RW_LIBSIZE_THRESHOLD: 0.05
RW_RELAB_THRESHOLD: 0.05
COVAR_L: []
# list of covariates to be used in the final stage of data cleaning/complete confounding calculations + data saving
# in our case, only ['disease', 'gender', 'age_category'] for CMD/IBD datasets are used, otherwise all empty

### BENCHMARK PHASE ###
post_integration_outputs: './benchmark/benchmarked_results'
used_R_methods: ["combat_seq", "limma", "MMUPHin", 'ConQuR', 'ConQuR_libsize']
used_Python_methods: ['harmony', "percentile_norm"]
batch_ref: 'cdi_youngster'
covar: ['DiseaseState']
condition_value: 'ASD'


### EVALUATION PHASE ###
evaluation_outputs: './outputs'
binarizing_agent: 'H' # for two microbiomeHD datasets or 'IBD' for ibd or 'adenoma' for the CRC dataset

